### ISSUE TITLE
panic: interface conversion: interface is nil, not *dom4g.Element

### ISSUE THREAD

**Issue by coder-han** [donnie4w/dom4g#1]
elemt := dom4g.NewElement("a", "a")
fmt.Print(elemt.ToXML())

报错，这是什么原因

**Comment by donnie4w** [comment]
thx！NewElement方法有bug
已经修改了

**Comment by donnie4w** [comment]
多谢反馈！修改后的程序己经更新到github.

coder-han notifications@github.com编写：
